default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: flights
  username: docker
  password: docker
  port: 54320
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
